model: simple
ckpt: data/ckpt/simple/simple_linear_one.ckpt
data:
  dataset: 'simple'
  settings:
    num_samples: 100
    distribution: 2
trainer:
  max_epochs: 1
  accelerator: gpu
  early_stopping:
    monitor: train_loss
    mode: min
  timer: true