model: resnet
ckpt: data/ckpt/resnet/resnet_pretrained.ckpt
data:
  dataset: images
  settings:
    num_samples: 1000
    num_classes: 3
    distribution: shifted
trainer:
  max_epochs: 1
  accelerator: gpu
  early_stopping:
    monitor: train_loss
    mode: min
  timer: true
