model:
  num_channels: 2
  initial_filters: 5
  complexity_factor: 1.67
  progression_factor: 2
  depth: 12

training:
  batch_size: 16
  learning_rate: 1e-4
  max_epochs: 10
  gpus: 1      # e.g., set 0 for CPU-only, or >1 if multi-GPU
  num_workers: 4

data:
  hdf5_folder: "data/hdf5"
