[project]
name = "usleep-adaptation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "commonsleepdatapipeline",
    "lightning>=2.5.0.post0",
    "mlarchitectures",
    "numpy>=1.17.3",
    "peft>=0.14.0",
    "pydantic>=2.10.6",
    "scikit-learn>=1.3.2",
    "scipy>=1.11.4",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121" },
]
torchvision = [
    { index = "pytorch-cu121" },
]
commonsleepdatapipeline = { git = "https://gitlab.au.dk/tech_ear-eeg/sleep-code/common-sleep-data-pipeline.git", rev = "main" }
mlarchitectures = { git = "https://gitlab.au.dk/tech_ear-eeg/ml_architectures.git", rev = "main" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
