model: usleep
ckpt: data/ckpt/usleep/alternative_big_sleep.ckpt
data:
  dataset: 'eesm19'
  settings:
    split_percentages: [0.8, 0.1, 0.1]
    batch_size: 64
    num_workers: 1
trainer:
  max_epochs: 100
  accelerator: gpu
  early_stopping:
    monitor: val_kappa
    mode: max
  timer: true