method: conv-adapter
parameter_count: grad
settings:
  forward_pass: parallel
  activation: relu
  reduction: 3
  layer: True
optimizer_settings: 
  lr: 1e-3
  lr_patience: 5
  lr_factor: 0.5
  lr_minimum: 1e-7