default: !include _default.yaml
method: conv-adapter
parameter_count: grad
settings:
  forward_pass: sequential
  activation: relu
  reduction: 5
  layer: True
optimizer_settings : 
    lr: 1e-4
    lr_patience: 5
    lr_factor: 0.5
    lr_minimum: 1e-7